# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1110c4254ae1e23050a687923c826aa10e59acc6f7ca93bf53900585e1e978564372480a3b0fabdb8cb747cbc42ea1e182eb01e1d82a342fd7ba2825a6e69810

test:
  secret_key_base: a0b610adf3cf9e3c71d4cbe31d3de24b8830017fec8598cfd14a955cb74f264e6312cca9b216cd635e04b8b9456ecf4add741f266f1626c40867ffa94fc50a40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
